All changes through sprint 3 (#1)
* Fixed friends subcommand help message

* Edited case for joke for a more polished format.

* Formatting...

* Formatting again, sorry lol

* PLEASE FORMAT RIGHT THANK YOU

* This is embarrassing.

* Added whiteboard to server

* Added whiteboard commands to client

* Updated whiteboard command names

* Added whiteboard to help command

* Revert "Added execute permissions+unix file formatting in .sh files"

This reverts commit 028d857781e463c21369c0504f8630636801fa83.

* filled in printMenu()

* Reverting files for merging into dev

* menu to print available shop commands to player

* fixed the sh file

* fixed sh

* fixed sh

* added the call to toString to print out shop specific greeting

* fixed sh

* added DailyLogger.java and added logging functionality

* Added demoable world to showcase feature

* Undo 208 change

* answers are no longer case sensitive

* FINALLY got the chat filter working. Chat filtering is now part of the player class.

* Fixed runServer.sh

* Added heartbeat protocol

* Renamed hb thread. Attempted to reset formatting

* Fixed line ending formatting

* fixed deleted curly bracket

when I was resolving the merge conflicts from 605b to dev I accidentally deleted a line (the curly bracket)

* removed print menu guts

removed print menu guts since everything seems to be in shopclient

* removed bad/uneeded code

removed code that people forgot to delete i guess

		System.out.println("Type the item you want to sell");
		sc = new Scanner(System.in);
		s = sc.nextLine();
		
		this.sell(s);
		
		System.out.println("Type the item you want to sell");
		sc = new Scanner(System.in);
		s = sc.nextLine();
		
		this.buy(s);

* removed commented code

removed priate shop shop
was commented out and TA yelled at me last time comment code was kept in

* removed old code people didn't delete

removed redundant/not working code

System.out.println("Type the item you want to sell");
		sc = new Scanner(System.in);
		s = sc.nextLine();
		
		this.sell(s);
		
		System.out.println("Type the item you want to sell");
		sc = new Scanner(System.in);
		s = sc.nextLine();
		
		this.buy(s);

* removed commented code

removed private shop shop

* fixed spacing in shopping loop

* Custom command can be a function without argument

* Now asks for multiple recovery questions, with ability to semi-easily
change the amount.

* Pick R-P-S to win at PvP

* removed logs directory and added code to create logs directory

* I really, truely believe that it works now. Had to fix some formatting issues, and move a lot of the message printing into the player class.

* Added the ability to save/read files for each player name. Made testing more effective.

* Does not allow to be challenged without finishing R-P-S game first

* rps

* reject

* Fixed error where print statements appear in server log instead of client stdout

* Changed variable name command to input

* Removed irrelevant comment

* Changed variable name again

* revert to gildir

have to revert to gildir to avoid merge conflict

* revert to gildir

have to revert to gildir to avoid merge conflict

* revert to gildir

have to revert to gildir to avoid merge conflict

* made command conform more to other features

* 805 fix again

* Fix rejection message in 805

* Fix PvP

* fixed bug in modified Room constructor

* Added sections, and shop section

* Update README.md

Added image

* Update and rename README.md to Shops.md

* fixed merge conflict

* added logging for whiteboard functions

* made venmo.send static and the amount rounding earlier

* Changed rate for checking client connection

* Revert "Team 7 Sprint 1 "

* Revert "310 redo command"

* init with sprint1

* re-building branch after upstream repo reset

* fixed things

* Rebuild 4011_Joke into sprint2 after upstream reset

* rebuild Joke after upstream reset

* Rebuild ChatLog after upstream reset

* fixed the teach, only available in room 1

* working files with lastest gidlr dev branch

* Add files via upload

* Merge 801,802

* Merged upstream/dev as of 10-30

* Delete CommandShortcut.xml

* compiles now

* God. Please make this the last commit

* fixed the redo command

* Revert "Team 8 301 Fixes many things"

* Delete CommandShortcut.xml

* Delete log 10-31-2018.txt

* fixing more stuff

* Moved instruction set to help.xml

* Revert "Team 7 Sprint 1"

* fixes more merge conflicts

* Update GameCore.java

* Update GameCore.java

* Update GameCore.java

* style to match gildir

* Delete CommandShortcut.xml

* Merge upstream/dev as of 10/31 afternoon

* Merged upstream/dev after PR #88 on 10/31

* Update runServer.sh

* Playing merge-race with Bhar :)

* merge after PR #70 was pulled in

* Merged upstream/dev after PR #70 revision

* and again

* Removed test files for word filter

* Delete Shops.md

* Revert "102 world files"

* Delete log 10-31-2018.txt

* revert Map.java

* added readme stuff

* merged new upstream/dev/

* removed duplicate methods from merge.  Note: a previous PR introduced a bug preventing the project from compiling.
GameServer.java:47: error: unreported exception IOException; must be caught or declared to be thrown.

* Fixed bug in upstream/dev/src/GameServer.java
Added try/catch IOException -Pat

* checked out upstream/dev/src/runServer.sh

* Moved instruction to help.xml

* Removed semicolon per the TA's request

* Added DELETE command to help xml

* Revert "Shop readme"

* Update runServer.sh

* Update runServer.sh

* Delete README.md

* Redid feature branch

* Redid feature branch

* Fixed formatting and item unmarshal

* Fixed runServer bat

* removed ignored players from player marshal. Further action needed

* Revert "Team-3 Section-004 Sprint-1"

* Readd Sprint1 tasks

* Fixed scripts

* Added back our features

* Fixed player formatting

* Format fix